### PR TITLE
Move from Sass to Less

### PR DESCRIPTION
**Pull request by mattstauffer**

### CODE REVIEW

**Comment by GrimLink** [comment]
@mattstauffer why do you want this?
Most CSS frameworks are SCSS based.

Also, this would be better as an option.
Instead setting it hard to LESS.

**Comment by mattstauffer** [comment]
@GrimLink Sass is heavier on the server, slower, and, while it originally had a lot more than Less does, no longer has enough to offer to make it worth it.

Anything is an option. Once you generate your app, you can just... change it. :)

**Comment by incraigulous** [comment]
I want to officially vote against merging this in. SCSS is more popular now days, not to mention it's the default in Laravel.

**Comment by damiani** [comment]
I'm gonna close this—at this point, I think we should probably remove the Sass default entirely, and ship with Tailwind instead :)

**Comment by mattstauffer** [comment]
Amen!

**Comment by incraigulous** [comment]
Amen!

**Pull request closed without merging**
