### PR TITLE
Refactor buildSite() method

### PR DESCRIPTION
**Pull request by cambri**
Substitute for handling collection on build site execution - collection class should likely be injected into the class (L4, L5) or method (L5)  but was creating dependency issues during debugging so it was initiated within the method for further code execution

### CODE REVIEW

**Comment by adamwathan** [comment]
Can you explain what bug or issue this is trying to solve exactly? It looks like this implementation is incorrect, there is no need for the `foreach` loop, you don't use the `$file` variable you get in each iteration and it causes the whole set of files to be built once for every file rather than once overall.

**Comment by cambri** [comment]
The code was dying here on build.  The collect() was not working for me.  I am using L4 so it might operate differently.  I went with for each loop for file because it looked to me as $file was not set in the original method.  This code did build out site directory with good structure.  My first pull request ever and I've messed it up, my social coding career has died before it even started.

**Comment by adamwathan** [comment]
Hahaha, no sweat, what do you mean you are using L4? Jigsaw defines it's own dependencies, so it should always be using a 5.x version of the Illuminate components:

https://github.com/tightenco/jigsaw/blob/master/composer.json#L19

**Comment by cambri** [comment]
I refactored all the components and dependencies to work with L4

**Pull request closed without merging**
