### PR TITLE
Add ability to minify the output html.

### PR DESCRIPTION
**Pull request by pabloleone**
Improve documentation for future contributors.

### CODE REVIEW

**Comment by damiani** [comment]
This doesn't feel like it belongs as a `config` option, but is pretty trivial to implement if you're using `gulp`. You can add a gulp task to `gulpfile.js` that runs after the site is built (so, after the `.exec` line), which runs `gulp-htmlin` on the `build` directory. Check out https://github.com/jonschlinkert/gulp-htmlmin for usage, and https://github.com/kangax/html-minifier for various config options.

**Comment by mattstauffer** [comment]
@damiani I agree. But thanks for the pull request @pabloleone!

**Comment by nicolaskopp** [comment]
sorry for the bump, but is there now an easy way to minify html output? I stumbled upon this one https://www.npmjs.com/package/minify-html-webpack-plugin but it does not seem to do anything.

**Comment by bakerkretzmar** [comment]
It's still possible but not with webpack/mix, you'd have to do it in PHP. You could handle it in an event listener when the Jigsaw build has finished.

**Comment by nicolaskopp** [comment]
Thank you, @bakerkretzmar, I will take a look. Maybe @pabloleone's PR can serve me as a starting point.

**Comment by nicolaskopp** [comment]
Okay FYI, the Event `getOutputPaths(`) as well as _getPages()_ is buggy and does in fact **not** deliver the generated html files, instead, the first file is empty for me and these events will only give me flat files like css, png, js and so on. Will file a bug report soon. For now, what I came up with is this. Please don't hit me, it works (for me), Normally not a PHP developer :)


set    ` 'minify_html' => true ` in config.php.

_bootstrap.php:_

```PHP
// minify html quick & dirty

function getDirContents($dir, $filter = '', &$results = [])
{
    $files = scandir($dir);

    foreach ($files as $key => $value) {
        $path = realpath($dir . DIRECTORY_SEPARATOR . $value);

        if (!is_dir($path)) {
            if (empty($filter) || preg_match($filter, $path)) $results[] = $path;
        } elseif ($value != "." && $value != "..") {
            getDirContents($path, $filter, $results);
        }
    }

    return $results;
}

$events->afterBuild(function ($jigsaw) {
    if (!is_null($jigsaw->getConfig('minify_html')) && $jigsaw->getConfig('minify_html') == true) {

        // this one is the only Event that actually wokrs for me and that I could use.
        $destination_path = $jigsaw->getDestinationPath();
        $html_files       = collect(getDirContents($destination_path, '/\.html$/'));

        $html_files->each(function ($item) use ($jigsaw, $destination_path) {

            // transform aboslute paths to relative paths again
            $relative_html_file = str_replace($destination_path, '', $item);
            $current_file_content = $jigsaw->readOutputFile($relative_html_file);


            //remove redundant (white-space) characters
            $replace          = [
                //remove tabs before and after HTML tags
                '/\>[^\S ]+/s'                                                    => '>',
                '/[^\S ]+\</s'                                                    => '<',
                //shorten multiple whitespace sequences; keep new-line characters because they matter in JS!!!
                '/([\t ])+/s'                                                     => ' ',
                //remove leading and trailing spaces
                '/^([\t ])+/m'                                                    => '',
                '/([\t ])+$/m'                                                    => '',
                // remove JS line comments (simple only); do NOT remove lines containing URL (e.g. 'src="http://server.com/"')!!!
                '~//[a-zA-Z0-9 ]+$~m'                                             => '',
                //remove empty lines (sequence of line-end and white-space characters)
                '/[\r\n]+([\t ]?[\r\n]+)+/s'                                      => "\n",
                //remove empty lines (between HTML tags); cannot remove just any line-end characters because in inline JS they can matter!
                '/\>[\r\n\t ]+\</s'                                               => '><',
                //remove "empty" lines containing only JS's block end character; join with next line (e.g. "}\n}\n</script>" --> "}}</script>"
                '/}[\r\n\t ]+/s'                                                  => '}',
                '/}[\r\n\t ]+,[\r\n\t ]+/s'                                       => '},',
                //remove new-line after JS's function or condition start; join with next line
                '/\)[\r\n\t ]?{[\r\n\t ]+/s'                                      => '){',
                '/,[\r\n\t ]?{[\r\n\t ]+/s'                                       => ',{',
                //remove new-line after JS's line end (only most obvious and safe cases)
                '/\),[\r\n\t ]+/s'                                                => '),',
                //remove quotes from HTML attributes that does not contain spaces; keep quotes around URLs!
                '~([\r\n\t ])?([a-zA-Z0-9]+)="([a-zA-Z0-9_/\\-]+)"([\r\n\t ])?~s' => '$1$2=$3$4', //$1 and $4 insert first white-space character found before/after attribute
            ];
            
            
            $new_file_content = preg_replace(array_keys($replace), array_values($replace), $current_file_content);

            //remove optional ending tags (see http://www.w3.org/TR/html5/syntax.html#syntax-tag-omission )
            $remove           = [
                '</option>', '</li>', '</dt>', '</dd>', '</tr>', '</th>', '</td>'
            ];
            
            $new_file_content = str_ireplace($remove, '', $new_file_content);

            $jigsaw->writeOutputFile($relative_html_file, $new_file_content);
        });
    }
});
```

**Comment by nicolaskopp** [comment]
Update minify function according to https://github.com/tighten/jigsaw/issues/602#issuecomment-994091880

```PHP
function minify($file_path, $jigsaw) {
    $current_file_content = $jigsaw->readOutputFile($file_path);

    //remove redundant (white-space) characters
    $replace = [
        //remove tabs before and after HTML tags
        '/\>[^\S ]+/s'                                                    => '>',
        '/[^\S ]+\</s'                                                    => '<',
        //shorten multiple whitespace sequences; keep new-line characters because they matter in JS!!!
        '/([\t ])+/s'                                                     => ' ',
        //remove leading and trailing spaces
        '/^([\t ])+/m'                                                    => '',
        '/([\t ])+$/m'                                                    => '',
        // remove JS line comments (simple only); do NOT remove lines containing URL (e.g. 'src="http://server.com/"')!!!
        '~//[a-zA-Z0-9 ]+$~m'                                             => '',
        //remove empty lines (sequence of line-end and white-space characters)
        '/[\r\n]+([\t ]?[\r\n]+)+/s'                                      => "\n",
        //remove empty lines (between HTML tags); cannot remove just any line-end characters because in inline JS they can matter!
        '/\>[\r\n\t ]+\</s'                                               => '><',
        //remove "empty" lines containing only JS's block end character; join with next line (e.g. "}\n}\n</script>" --> "}}</script>"
        '/}[\r\n\t ]+/s'                                                  => '}',
        '/}[\r\n\t ]+,[\r\n\t ]+/s'                                       => '},',
        //remove new-line after JS's function or condition start; join with next line
        '/\)[\r\n\t ]?{[\r\n\t ]+/s'                                      => '){',
        '/,[\r\n\t ]?{[\r\n\t ]+/s'                                       => ',{',
        //remove new-line after JS's line end (only most obvious and safe cases)
        '/\),[\r\n\t ]+/s'                                                => '),',
        //remove quotes from HTML attributes that does not contain spaces; keep quotes around URLs!
        '~([\r\n\t ])?([a-zA-Z0-9]+)="([a-zA-Z0-9_/\\-]+)"([\r\n\t ])?~s' => '$1$2=$3$4', //$1 and $4 insert first white-space character found before/after attribute
    ];


    $new_file_content = preg_replace(array_keys($replace), array_values($replace), $current_file_content);

    //remove optional ending tags (see http://www.w3.org/TR/html5/syntax.html#syntax-tag-omission )
    $remove = [
        '</option>', '</li>', '</dt>', '</dd>', '</tr>', '</th>', '</td>'
    ];

    $new_file_content = str_ireplace($remove, '', $new_file_content);

    $jigsaw->writeOutputFile($file_path, $new_file_content);
}

$events->afterBuild(function ($jigsaw) {
    if (!is_null($jigsaw->getConfig('minify_html')) && $jigsaw->getConfig('minify_html') == true) {

        $build_files = $jigsaw->getOutputPaths();
        $build_files->each(function ($item) use ($jigsaw) {

            if (gettype($item) == "string") {
                if (strlen($item) == 0) {
                    $item = "/index.html";
                }

                if (str_contains($item, ".html")) {
                    minify($item, $jigsaw);
                }
            }
        });
    }
});
```

**Pull request closed without merging**
