### PR TITLE
Add ability to register custom blade tags

### PR DESCRIPTION
**Pull request by TheNodi**
See #67.

To register a blade directive:
```php
<php
// blade.php

return [
    'datetime' => function ($expression) {
      return '<?php echo date("Y-m-d H:i:s", ' . $expression . '); ?>';
    }
];
```

I didn't add the $page parameter because it was calculated using get_defined_vars() on the resolved blade instance.

### CODE REVIEW

**Comment by damiani** [comment]
Excellent! I think we should change the name from `BladeFile` to `BladeDirectivesFile` so it doesn't get confused with the `BladeHandler`. After that change, it's good to go!

**Comment by TheNodi** [comment]
Sure, done!

**Comment by damiani** [comment]
Thanks for this contribution, @TheNodi! 👍

**Comment by damiani** [comment]
Yes, this was added before component and include aliasing was added to Laravel, but it would be worthwhile supporting this. For now, though, I don't want to introduce a breaking change for anyone using the current method of registering directives. We can expose the `BladeCompiler` to `blade.php` easily, though, by passing it to the constructor of `BladeDirectivesFile` and assigning it to `$bladeCompiler`, rather than injecting it in the `register` method. I'd welcome a PR with that approach!

**Comment by JoshMoreno** [comment]
Yea agree on not introducing breaking changes. Too quick.

Here ya go #204

**Pull request merged**
