### PR TITLE
Fix init command

### PR DESCRIPTION
**Pull request by carbontwelve**
I notice that the init command would crash if the directory existed, it now gracefully exits with a notification for why.

### CODE REVIEW

**Comment by carbontwelve** [comment]
I have also added a unit test to ensure that my fix didn't break anything.

**Comment by adamwathan** [comment]
Awesome thanks a ton! Do you mind going over the PR and updating the code style to match PSR-2? Happy to merge then :+1:

**Comment by carbontwelve** [comment]
Of course, I will review and amend where necessary.

**Comment by carbontwelve** [comment]
I think this is done, phpcs is complaining about line lengths but PSR-2 states those to not be hard limits, plus line endings but I think git converts those on push.

**Comment by adamwathan** [comment]
Accidentally fixed this by changing how the site is init'd, heh... Sorry :(

**Comment by carbontwelve** [comment]
No worries :)

**Pull request closed without merging**
